Feature/economy
kevincerro-dvrv/dxpp-gdd pull request #6
Opened 2023-12-05 19:33 UTC by diegoAG100

Bases de la economía:
[x] Como se consiguen los puntos
[x] Como funcionan los puntos
[x] Donde te puedes gastar los puntos

2023-12-05 20:02 UTC, kevincerro-dvrv requested changes
Please use a spell checker and rewrite using third person

- tendra => tendrá
- conseguiras => conseguirás
- etc

2023-12-14 18:39 UTC, BraisGlezArias commented on economy.md
> +El juego tendra un sistema de puntos, estos puntos serán **compartidos por todo el equipo**, se conseguirán puntos haciendo daño a zombies y dependiendo de la parte en la que el jugador dispare recib
tendrá

2023-12-14 18:41 UTC, BraisGlezArias commented on economy.md
> +Con los puntos se podrán **comprar diferentes objetos y consumibles** en una tienda que estará en una esquina del mapa, podran salir un número aleatorio de objetos que se podrán comprar, la cantidad
podrán, número, máximo, mínimo, rellenarán

2023-12-14 18:41 UTC, BraisGlezArias commented on economy.md
> +Habrá una maquina de mejoras que **gastara 4000 puntos** para poder usarse y permitirá al jugador **mejorar un arma** hasta 2 veces.
gastará

2023-12-14 18:42 UTC, BraisGlezArias requested changes
Revisa acentos.

2023-12-14 18:48 UTC, kevincerro-dvrv commented on economy.md
> +Si no se falla ningún disparo durante 15 balas seguidas, las siguientes balas hasta que se falle darán un **50% más de puntos**.
```suggestion
Si no se falla ningun disparo durante 15 balas seguidas, las siguientes balas hasta que se falle darán un **50% más de puntos**.
```

2023-12-14 18:58 UTC, BraisGlezArias approved these changes
Todo correcto.

2023-12-14 18:59 UTC, kevincerro-dvrv approved these changes

2023-12-14 18:59 UTC, merged